# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  publish:
    branches:
      only: master
    docker:
      - image: circleci/clojure:lein-2.7.1

    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - run: lein deploy clojars

  vsts-push:
    docker:
      - image: circleci/clojure:lein-2.7.1
    working_directory: ~/repo
    steps:
      - add_ssh_keys
      - checkout
      - run: ssh-keyscan vs-ssh.visualstudio.com >> ~/.ssh/known_hosts
      - run: git push ssh://2018-PCS2044-LAMBDA@vs-ssh.visualstudio.com:22/quack-pack/_ssh/service-template master


workflows:
  version: 2
  test-publish:
    jobs:
      - vsts-push:
          filters:
            branches:
              only: master
          requires:
            - test
      - publish:
          filters:
            branches:
              only: master
          requires:
            - vsts-push
